### ISSUE TITLE
Issue setting up APIs

### ISSUE THREAD

**Issue by Strandz1** [samc621/SneakerBot#69] opened 2022-02-04 11:24 UTC
Hey I have managed to get the bot started up until the (npm start) command and I am struggling with getting the APIs to send the address, task and proxy information to the relevant port. I copied the code from the POST website and filled it in with my details and for the URL I put http://127.0.0.1:8080/(the relevant part). However when I input this curl command into the terminal it says several erros such as (Bad URL, unexpected token " in JSON etc.) I have a hunch that I a simply inputing the wrong code or in the wrong place. If you could help me that would be much appreciated. Thnks

![IMG_0188](https://user-images.githubusercontent.com/99020429/152520976-653251d7-22a2-4c98-bfc9-32a4c6e59bba.jpg)

**Comment by samc621** [comment] 2022-02-04 17:54
@Strandz1 looks like you have the server running, nice! Can you show me the request you are making to the API? This error suggests that there's something wrong with the request payload or a missing/wrong header that's causing Express to fail to parse it.

**Comment by Strandz1** [comment] 2022-02-04 18:12
Thanks for the reply! So I have also discovered that when I run " npm run lint " this error appears...![image](https://user-images.githubusercontent.com/99020429/152580299-4d11b489-1f00-4a44-89fb-848c708bead9.jpeg)

I'm not sure if this is related to the issue but yh. I have attached below a screenshot of the command I inputted and the result it gave. 
Thanks again!              [image](https://user-images.githubusercontent.com/99020429/152581173-5b20b1cc-3980-436e-9562-fa17b334d0f0.jpeg)

![image](https://user-images.githubusercontent.com/99020429/152581006-edc98619-6a05-447e-a95a-1ef1a33e81d2.jpeg)

**Comment by samc621** [comment] 2022-02-04 19:22
@Strandz1 thanks for mentioning the linting errors, I will fix those.

Looks like your error is caused by the spaces around the URI. Try `"http://127.0.0.1:8080/v1/addresses"` (no spaces inside the quotes).

**Comment by Strandz1** [comment] 2022-02-04 19:26
I tried that and it comes up with curl: (3) URL using bad/illegal format or missing URL

**Comment by samc621** [comment] 2022-02-04 20:55
@Strandz1 oh sorry, you will need to use single quotes as well.

**Comment by Strandz1** [comment] 2022-02-05 11:24
![image](https://user-images.githubusercontent.com/99020429/152640006-93ce5a55-31f7-491a-8936-5aead22b9a5d.jpeg)

Hey, it still shows this error

**Comment by Strandz1** [comment] 2022-02-05 11:26
![image](https://user-images.githubusercontent.com/99020429/152640108-a9931512-7f6f-4f4a-b4f2-a1dc3ddf92bb.jpeg)
Hey it still shows this error

**Comment by samc621** [comment] 2022-02-05 12:55
@Strandz1 the picture is very blurry, I suggest using screenshots. From what I can see, your issue now is that you have an open quote and no closing quote around the URI...

**Comment by Strandz1** [comment] 2022-02-05 16:20
I figured out how to make the link work but now it hits me with this
<img width="1396" alt="Screenshot 2022-02-05 at 16 19 05" src="https://user-images.githubusercontent.com/99020429/152649719-1980135e-235a-47c1-8cf1-ae337f7bd1a5.png">

**Comment by samc621** [comment] 2022-04-01 01:55
Hi @Strandz1, I am hoping you've resolved this issue by now. I am going to close it, feel free to open a new one if the issues persist.

**Closed by samc621** 2022-04-01 01:55 UTC
