### ISSUE TITLE
Docker with docker-compose build error

### ISSUE THREAD

**Issue by marrik96** [samc621/SneakerBot#64] opened 2022-01-10 18:29 UTC
Configured Dockerfile, .env.docker, db-data folder.  docker-compose dies at step 18/20

....
Step 18/20 : RUN chmod +x ./container_start.sh
 ---> Running in 05025cd59ad0
chmod: cannot access './container_start.sh': No such file or directory
ERROR: Service 'server' failed to build: The command '/bin/sh -c chmod +x ./container_start.sh' returned a non-zero code: 1

**Comment by samc621** [comment] 2022-01-11 00:56
Hi @marrik96 thanks for pasting the error output. This is weird, because the file is definitely there. Can you let me know what OS you are on, and what version of Docker and Docker Compose you are using? I will try to reproduce this error when I find a minute.

**Comment by marrik96** [comment] 2022-01-11 14:53
Ubuntu 20.04.3 LTS
Docker version 20.10.12, build e91ed57

Is the file something that is downloaded via script, or I should manually download?  In my docker directory I have the following files.  Dockerfile, docker-compose.yml, package.json, and db-data directory.

Thanks for assisting!

**Comment by samc621** [comment] 2022-01-11 15:11
The file is in the root directory, you should see it there. Did you create a separate directory with those files? Or are you referring to a directory inside the Docker container? That seems not necessary. If you run docker-compose from the root directory, it should work fine.

**Comment by marrik96** [comment] 2022-01-11 15:14
I created a "sneakerbot" directory and put all files there.
![2022-01-11_9-13-03](https://user-images.githubusercontent.com/22241571/148969179-bff8ff19-8646-44a0-96b5-94cd05a85543.png)

**Comment by samc621** [comment] 2022-01-11 15:25
This is going to work, the error makes sense now. You need to put all of the files there, or just run Docker commands from the root directory of the project. You can't build the Docker image with missing files.

**Comment by marrik96** [comment] 2022-01-11 15:32
yeah.  dumb on my part.  I did not clone repo.  I just grabbed the few files I thought I needed.  It worked!

![image](https://user-images.githubusercontent.com/22241571/148972461-7c135c55-3233-42b4-8735-ecbe5934d6e8.png)

**Comment by samc621** [comment] 2022-01-11 15:34
Ok great! Closing this for now, feel free to open a new issue if anything comes up.

**Closed by samc621** 2022-01-11 15:34 UTC
