### ISSUE TITLE
Not in cart, trying again

### ISSUE THREAD

**Issue by willymmerlet12** [samc621/SneakerBot#67] opened 2022-01-26 22:07 UTC
While making a task for nike.com I get this error and throw the bot to login on your nike account.
<img width="1183" alt="Screenshot 2022-01-26 at 17 02 53" src="https://user-images.githubusercontent.com/60224467/151254793-a89c0b3b-92a6-4e02-ba0a-e922a1fcb51c.png">

This is my log :
<img width="449" alt="Screenshot 2022-01-26 at 17 03 17" src="https://user-images.githubusercontent.com/60224467/151254878-ea4106b3-8949-4379-a026-41d2de65b2a4.png">

Task request:
<img width="543" alt="Screenshot 2022-01-26 at 17 03 44" src="https://user-images.githubusercontent.com/60224467/151254932-619c65bc-d7ba-4444-a223-e87b39c94528.png">

Proxie request:
<img width="518" alt="Screenshot 2022-01-26 at 17 03 33" src="https://user-images.githubusercontent.com/60224467/151255047-958e65e5-4427-46ce-829f-a2bd277feba1.png">

**Comment by samc621** [comment] 2022-01-26 22:17
It's hard for me to understand the specific issue you're facing based on your message and screenshots, but think that this is a duplicate of #28, please find more information there. Closing this.

**Closed by samc621** 2022-01-26 22:17 UTC
